  <option value="">Category</option>
  <option value="Community">Community</option>
  <option value="Social Service">Social Service</option>
  <option value="Languages" >Languages</option>
  <option value="Personal Development">Personal Development</option>
  <option value="Fashion">Fashion</option>
  <option value="Sports">Sports</option>
  <option value="Career">Career</option>
  <option value="Education">Education</option>
  <option value="Medical">Medical</option>
  <option value="Music">Music</option>
  <option value="Religious">Religious</option>
  <option value="Travel">Travel</option>
  <option value="Writing">Writing</option>
  <option value="Politics">Politics</option>
  <option value="Technology">Technology</option>
  <option value="Science">Science</option>
  <option value="Children">Children</option>
  <option value="Spiritual">Spiritual</option>
  <option value="Family">Family</option>
  <option value="Leisure">Leisure</option>
